### ISSUE TITLE
formatMessage is undefined

### ISSUE THREAD

**Issue by TinChak** [lym0r9/wechat-mp#1]
https://github.com/lym0r9/wechat-mp/blob/d3ede1fe773ef7bede0cb9f4d6824462d9f5eb71/utils/mUtils.js#L44

**Comment by lym0r9** [comment]
此处的formatMessage是个递归调用自己，修改函数名时忘记改函数内的调用。
https://github.com/lym0r9/wechat-mp/blob/14a84dcca8c912eb220a94bc21b95a440b027e55/utils/mUtils.js#L44
